### ISSUE TITLE
Daylights savings time is not calculated

### ISSUE THREAD

**Issue by erens-basement** [KevinNovak/Friend-Time#46] opened 2020-07-18 08:47 UTC
When times are entered as EST or ET, daylights savings is not automatically calculated. Even worse, if users select their time zone based on a region like America/New York, it defaults to the DST off time zone. 

This is an issue because half the world is on an adjusted daylights time and most of my users are inputting their location or a non daylights time causing an hour off difference. 

DST should automatically be calculated or this bot is useless for half the year.

**Comment by KevinNovak** [comment] 2020-12-19 02:33
Duplicate of #42

**Closed** 2020-12-19 02:34 UTC
Labels: duplicate
