### ISSUE TITLE
Automatically correct inapplicable time zones

### ISSUE THREAD

**Issue by nomis** [KevinNovak/Friend-Time#54] opened 2020-10-09 16:57 UTC
People frequently can't use timezones correctly.

They refer to "3pm pst" when DST is in effect. The bot takes this literally and conversion is then an hour out, because they really meant "3pm pdt".

The bot needs to assume people are wrong when they use time zones in a time period where they are not in effect. For example, if they specify "3pm pst", assume they meant "3pm pt" ("3pm pdt") if the Pacific time zone on that date (and time) is PDT.

No amount of telling people that they're using the wrong time zone will get them to specify time correctly.

**Comment by KevinNovak** [comment] 2020-12-19 02:49
Duplicate of #42

**Closed** 2020-12-19 02:50 UTC
Labels: duplicate

**Comment by nomis** [comment] 2020-12-19 08:46
This is not a duplicate of #42.

You state in that issue that it only determines DST if not explicitly specified. This issue concerns people explicitly specifying the wrong DST status.
